it('succesfull register and delete',()=>{
    cy.visit('https://automationexercise.com')
    cy.contains('Home').should('be.visible')
    cy.contains('Signup').click()
    cy.contains('New User Signup!').should('be.visible')
    cy.get('[data-qa="signup-name"]').type('enea')
    cy.get('[data-qa="signup-email"]').type('enias_95@hotmail.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.contains('Enter Account Information').should('be.visible')
    cy.get('#id_gender1').click()
    cy.get('[data-qa="password"]').type('07110711di')
    cy.get('#days').select('27').should('have.value','27')
    cy.get('#months').select('July').should('have.value','7')
    cy.get('#years').select('1995').should('have.value','1995')
    cy.get('#newsletter').click()
    cy.get('#optin').click()
    cy.get('[data-qa="first_name"]').type('enea')
    cy.get('[data-qa="last_name"]').type('ntilka')
    cy.get('[data-qa="company"]').type('EniMa')
    cy.get('[data-qa="address"]').type('agatova 1')
    cy.get('#country').select('United States').should('have.value','United States')
    cy.get('[data-qa="state"]').type('bratislava')
    cy.get('[data-qa="city"]').type('ivanka pri dunaj')
    cy.get('[data-qa="zipcode"]').type('90028')
    cy.get('[data-qa="mobile_number"]').type('+30 6973946598')
    cy.get('[data-qa="create-account"]').click()
    cy.get('b').should('be.visible')
    cy.get('[data-qa="continue-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    cy.get('.shop-menu > .nav > :nth-child(5) > a').should('be.visible')
    cy.get('[data-qa="continue-button"]').click()



})