it('succesfull register and delete',()=>{
    cy.visit('https://automationexercise.com')
    cy.contains('Home').should('be.visible')
    cy.contains('Signup').click()
    cy.contains('New User Signup!').should('be.visible')
    cy.get('[data-qa="signup-name"]').type('enikooo')
    cy.get('[data-qa="signup-email"]').type('enikooo@example.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.contains('Enter Account Information').should('be.visible')
    cy.get('#id_gender1').click()
    cy.get('[data-qa="password"]').type('123456789')
    cy.get('#days').select('27').should('have.value','27')
    cy.get('#months').select('July').should('have.value','7')
    cy.get('#years').select('1995').should('have.value','1995')
    cy.get('#newsletter').click()
    cy.get('#optin').click()
    cy.get('[data-qa="first_name"]').type('enikoo')
    cy.get('[data-qa="last_name"]').type('example')
    cy.get('[data-qa="company"]').type('ftriko')
    cy.get('[data-qa="address"]').type('strasse')
    cy.get('#country').select('United States').should('have.value','United States')
    cy.get('[data-qa="state"]').type('bratislava')
    cy.get('[data-qa="city"]').type('cityname')
    cy.get('[data-qa="zipcode"]').type('123456')
    cy.get('[data-qa="mobile_number"]').type('4567318964')
    cy.get('[data-qa="create-account"]').click()
    cy.get('b').should('be.visible')
    cy.get('[data-qa="continue-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    cy.get('.shop-menu > .nav > :nth-child(5) > a').should('be.visible')
    cy.get('[data-qa="continue-button"]').click()



})
